createfigure([dists, nrms]);

function createfigure(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 26-Jul-2020 09:12:35

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to semilogy
semilogy1 = semilogy(YMatrix1,'LineWidth',2);
set(semilogy1(1),'DisplayName','$||x_k-x^*||$');
set(semilogy1(2),'DisplayName','$||\nabla f(x)||$');

% Create xlabel
xlabel('$k$','Interpreter','latex');

hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'ContextMenu','FontSize',24,'TickLabelInterpreter','latex',...
    'YMinorTick','on','YScale','log');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex');
title(legend1,'Exact Line Search');
end
